# Generated by Django 2.1.15 on 2019-12-16 11:37

from django.conf import settings
from django.contrib.auth import get_user_model
from django.contrib.contenttypes.models import ContentType
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('django_token_bucket', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='tokenbucket',
            old_name='user',
            new_name='object_id',
        ),
        migrations.AddField(
            model_name='tokenbucket',
            name='content_type',
            field=models.ForeignKey(default=ContentType.objects.get_for_model(get_user_model()).id, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tokenbucket',
            name='object_id',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='tokenbucket',
            unique_together={('identifier', 'object_id', 'content_type')},
        ),
    ]
