# Generated by Django 2.1.15 on 2020-01-11 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_token_bucket', '0003_auto_20200111_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokenbucket',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AlterUniqueTogether(
            name='tokenbucket',
            unique_together={('identifier', 'object_id', 'content_type')},
        ),
    ]
